=== giu300486/ai-answer/WebContent/xsd/questionario.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.tesi.org/questionario" xmlns:tns="http://www.tesi.org/questionario" elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:Q1="http://www.w3.org/2001/XMLSchema" xmlns:Q2="http://www.w3.org/2001/XMLSchema" xmlns:Q3="http://www.w3.org/2001/XMLSchema" xmlns:Q4="http://www.w3.org/2001/XMLSchema" xmlns:Q5="http://www.w3.org/2001/XMLSchema">

<!-- link http://www.dis.uniroma1.it/~rosati/lw-1314/slides-XML/lezione-5/lezione-5.html -->
	
			<element name="questionario">
				<complexType>
					<sequence>
						<sequence>
							<element name="classeAppartenenza"
								minOccurs="1" maxOccurs="unbounded">
								<complexType>
									<sequence>
										<element name="oggetto"
											minOccurs="1" maxOccurs="unbounded">
											<complexType>
												<attribute name="nome"
													use="required">
													<simpleType>
														<restriction
															base="string">
															<pattern
																value="[a-zA-Z0-9\s,']+">
															</pattern>
														</restriction>
													</simpleType>
												</attribute>
											</complexType>
										</element>
									</sequence>
									<attribute name="nome"
										use="required">
										<simpleType>
											<restriction
												base="string">
												<pattern
													value="[a-zA-Z0-9\s]+">
												</pattern>
											</restriction>
										</simpleType>
									</attribute>
								</complexType>
								<unique name="oggettoKey">
									<selector xpath="tns:oggetto"></selector>
									<field xpath="@nome"></field>
								</unique>
							</element>
						</sequence>
						<sequence>
							<element name="classeEsclusione"
								maxOccurs="unbounded" minOccurs="0">
								<complexType>
									<sequence>
										<element name="domanda"
											maxOccurs="unbounded" minOccurs="1">
											<complexType>
												<attribute name="nome"
													use="required">
													<simpleType>
														<restriction
															base="string">
															<pattern
																value="[a-zA-Z0-9]+">
															</pattern>
														</restriction>
													</simpleType>
												</attribute>
											</complexType>
										</element>
									</sequence>
									<attribute name="nome"
										use="required">
										<simpleType>
											<restriction
												base="string">
												<pattern
													value="[a-zA-Z0-9]+">
												</pattern>
											</restriction>
										</simpleType>
									</attribute>
								</complexType>
							</element>
						</sequence>
						<sequence>
							<element name="domanda"
								maxOccurs="unbounded" minOccurs="1">
								<complexType>
									<sequence maxOccurs="1"
										minOccurs="1">
										<element
											name="contenutoDomanda">
											<simpleType>
												<restriction
													base="string">
													<pattern
														value="[a-zA-Z0-9\s\?,']+">
													</pattern>
												</restriction>
											</simpleType>
										</element>
										<sequence>
											<element name="risposta"
												minOccurs="2" maxOccurs="unbounded">
												<complexType>
													<sequence
														maxOccurs="1" minOccurs="1">
														<element
															name="contenutoRisposta">
															<simpleType>
																<restriction
																	base="string">
																	<pattern
																		value="[a-zA-Z0-9\s,']+">
																	</pattern>
																</restriction>
															</simpleType>
														</element>
														<sequence>
															<element
																name="classeAppartenenza" minOccurs="1"
																maxOccurs="unbounded">
																<complexType>
																	<attribute
																		name="nome" use="required">
																		<simpleType>
																			<restriction
																				base="string">
																				<pattern
																					value="[a-zA-Z0-9\s]+">
																				</pattern>
																			</restriction>
																		</simpleType>
																	</attribute>
																</complexType>
															</element>
														</sequence>
														<element
															name="classeEsclusione" minOccurs="0" maxOccurs="1">
															<complexType>
																<attribute
																	name="nome" use="required">
																	<simpleType>
																		<restriction
																			base="string">
																			<pattern
																				value="[a-zA-Z0-9]+">
																			</pattern>
																		</restriction>
																	</simpleType>
																</attribute>
															</complexType>
														</element>
													</sequence>
													<attribute
														name="peso" use="required">
														<simpleType>
															<restriction
																base="int">
																<pattern
																	value="[0-9]+">
																</pattern>
															</restriction>
														</simpleType>
													</attribute>
												</complexType>
												<unique
													name="classeAppartenenzaK">
													<selector
														xpath="tns:classeAppartenenza">
													</selector>
													<field
														xpath="@nome">
													</field>
												</unique>
											</element>
										</sequence>
									</sequence>
									<attribute name="codiceDomanda"
										use="required">
										<simpleType>
											<restriction
												base="string">
												<pattern
													value="[a-zA-Z0-9]+">
												</pattern>
											</restriction>
										</simpleType>
									</attribute>
									<attribute name="precedenza"
										use="required">
										<simpleType>
											<restriction base="int">
												<pattern
													value="[0-9]+">
												</pattern>
											</restriction>
										</simpleType>
									</attribute>
								</complexType>
								<unique name="contenutoRispostaKey">
									<selector xpath="tns:risposta"></selector>
									<field
										xpath="tns:contenutoRisposta">
									</field>
								</unique>
							</element>
						</sequence>
					</sequence>
					<attribute name="nome" type="string"
						use="required">
					</attribute>
					<attribute name="abilita" type="boolean" use="required"></attribute>
					<attribute name="css" type="string" use="required"></attribute>
				</complexType>
				<unique name="classeAppartenenzaKey">
					<selector xpath="tns:classeAppartenenza"></selector>
					<field xpath="@nome"></field>
				</unique>
				<unique name="domandaKey">
					<selector xpath="tns:domanda"></selector>
					<field xpath="@codiceDomanda"></field>
		  		</unique>
			</element>

</schema>

=== giu300486/ai-answer/WebContent/xml/giu300486/questionarioComputer1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<tns:questionario xmlns:tns="http://www.tesi.org/questionario" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" abilita="false" css="/TESI-V2/xml/giu300486/mioCSS2.css" nome="questionarioComputer1" xsi:schemaLocation="http://www.tesi.org/questionario ../../xsd/questionario.xsd ">	  
  <tns:classeAppartenenza nome="costoMinore800">		    	
    	<tns:oggetto nome="PC700"/>		    	
    	<tns:oggetto nome="PC600"/>		
    	<tns:oggetto nome="PC500"/>		
    	<tns:oggetto nome="PC450"/>
		<tns:oggetto nome="PC750"/>
		<tns:oggetto nome="PC350"/>
	</tns:classeAppartenenza>
	<tns:classeAppartenenza nome="costoMaggioreUguale800">
		<tns:oggetto nome="PC800"/>
		<tns:oggetto nome="PC850"/>
		<tns:oggetto nome="PC900"/>
		<tns:oggetto nome="PC1000"/>
		<tns:oggetto nome="PC1500"/>
		<tns:oggetto nome="PC1300"/>
		<tns:oggetto nome="PC2000"/>
	</tns:classeAppartenenza>
  	<tns:classeAppartenenza nome="numeroProcessori2">
  		<tns:oggetto nome="PC500"/>
		<tns:oggetto nome="PC450"/>
		<tns:oggetto nome="PC350"/>
  	</tns:classeAppartenenza>
  	<tns:classeAppartenenza nome="numeroProcessori4">
  		<tns:oggetto nome="PC600"/>
		<tns:oggetto nome="PC700"/>
		<tns:oggetto nome="PC750"/>
  	</tns:classeAppartenenza>
  	<tns:classeAppartenenza nome="numeroProcessori8">
  		<tns:oggetto nome="PC800"/>
		<tns:oggetto nome="PC850"/>
		<tns:oggetto nome="PC900"/>
		<tns:oggetto nome="PC1000"/>
  	</tns:classeAppartenenza>
  	<tns:classeAppartenenza nome="numeroProcessori16">
  		<tns:oggetto nome="PC1500"/>
		<tns:oggetto nome="PC1300"/>
		<tns:oggetto nome="PC2000"/>
  	</tns:classeAppartenenza>
  	<tns:classeAppartenenza nome="RamMinoreUguale8">
  		<tns:oggetto nome="PC500"/>
		<tns:oggetto nome="PC450"/>
		<tns:oggetto nome="PC350"/>
		<tns:oggetto nome="PC600"/>
		<tns:oggetto nome="PC700"/>
		<tns:oggetto nome="PC750"/>
  	</tns:classeAppartenenza>
  	<tns:classeAppartenenza nome="RamMaggiore8">
  		<tns:oggetto nome="PC800"/>
		<tns:oggetto nome="PC850"/>
		<tns:oggetto nome="PC900"/>
		<tns:oggetto nome="PC1000"/>
		<tns:oggetto nome="PC1500"/>
		<tns:oggetto nome="PC1300"/>
		<tns:oggetto nome="PC2000"/>
  	</tns:classeAppartenenza>
  	  
  	<tns:classeEsclusione nome="C1">
  		<tns:domanda nome="D3"/>
  	</tns:classeEsclusione>
  	<tns:classeEsclusione nome="C2">
  		<tns:domanda nome="D2"/>
  	</tns:classeEsclusione>
  	<tns:classeEsclusione nome="C3">
   	<tns:domanda nome="D1"/>
     	<tns:domanda nome="D2"/>
      <tns:domanda nome="D3"/>
      <tns:domanda nome="D4"/>
   </tns:classeEsclusione>

	<tns:domanda codiceDomanda="D1" precedenza="0">
	  <tns:contenutoDomanda>Quanto e la spesa massima che vuoi affrontare?</tns:contenutoDomanda>
	  <tns:risposta peso="3">
	    <tns:contenutoRisposta>meno di 800 euro</tns:contenutoRisposta>
	    <tns:classeAppartenenza nome="costoMinore800"/>
	    <tns:classeEsclusione nome="C1"/>
	  </tns:risposta>
	  <tns:risposta peso="3">
	    <tns:contenutoRisposta>almeno di 800 euro</tns:contenutoRisposta>
	    <tns:classeAppartenenza nome="costoMaggioreUguale800"/>
	    <tns:classeEsclusione nome="C2"/>
	  </tns:risposta>
	</tns:domanda>

	<tns:domanda codiceDomanda="D2" precedenza="1">
		<tns:contenutoDomanda>Quale processori preferisci?</tns:contenutoDomanda>
		<tns:risposta peso="2">
			<tns:contenutoRisposta>Dual Core</tns:contenutoRisposta>
			<tns:classeAppartenenza nome="numeroProcessori2"/>
         <tns:classeEsclusione nome="C1"/>
		</tns:risposta>
		<tns:risposta peso="2">
			<tns:contenutoRisposta>Quad Core</tns:contenutoRisposta>
			<tns:classeAppartenenza nome="numeroProcessori4"/>
         <tns:classeEsclusione nome="C1"/>
		</tns:risposta>
	</tns:domanda>
	
	<tns:domanda codiceDomanda="D3" precedenza="1">
		<tns:contenutoDomanda>Quale processori preferisci?</tns:contenutoDomanda>
		<tns:risposta peso="2">
			<tns:contenutoRisposta>Octa Core</tns:contenutoRisposta>
			<tns:classeAppartenenza nome="numeroProcessori8"/>
         <tns:classeEsclusione nome="C2"/>
		</tns:risposta>
		<tns:risposta peso="2">
			<tns:contenutoRisposta>Exa Core</tns:contenutoRisposta>
			<tns:classeAppartenenza nome="numeroProcessori16"/>
         <tns:classeEsclusione nome="C2"/>
		</tns:risposta>	
	</tns:domanda>
	
	<tns:domanda codiceDomanda="D4" precedenza="2">
		<tns:contenutoDomanda>Quanta RAM preferisci?</tns:contenutoDomanda>
		<tns:risposta peso="2">
			<tns:contenutoRisposta>meno o pari a 8 GB</tns:contenutoRisposta>
			<tns:classeAppartenenza nome="RamMinoreUguale8"/>
         <tns:classeEsclusione nome="C3"/>
		</tns:risposta>
		<tns:risposta peso="2">
			<tns:contenutoRisposta>maggiore di 8 GB</tns:contenutoRisposta>
			<tns:classeAppartenenza nome="RamMaggiore8"/>
         <tns:classeEsclusione nome="C3"/>
		</tns:risposta>
	</tns:domanda>

</tns:questionario>

=== giu300486/ai-answer/WebContent/xml/giu300486/prova1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<tns:questionario xmlns:tns="http://www.tesi.org/questionario" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" abilita="false" css="/TESI-V2/xml/giu300486/mioCSS.css" nome="prova1" xsi:schemaLocation="http://www.tesi.org/questionario ../../xsd/questionario.xsd ">	
  <tns:classeAppartenenza nome="C1">		
    <tns:oggetto nome="O1"/>		
    <tns:oggetto nome="O2"/>		
    <tns:oggetto nome="O4"/>	
  </tns:classeAppartenenza>  
  <tns:classeAppartenenza nome="C2">  		
    <tns:oggetto nome="O2"/>  		
    <tns:oggetto nome="O4"/>
  	</tns:classeAppartenenza>
  	<tns:classeAppartenenza nome="C3">
  		<tns:oggetto nome="O1"/>
  		<tns:oggetto nome="O3"/>
  	</tns:classeAppartenenza>
  	<tns:classeAppartenenza nome="C4">
  		<tns:oggetto nome="O2"/>
  		<tns:oggetto nome="O3"/>
  	</tns:classeAppartenenza>

  	<tns:classeEsclusione nome="E1">
   	<tns:domanda nome="D1"/>
    	<tns:domanda nome="D2"/>
  	</tns:classeEsclusione>
   <tns:classeEsclusione nome="E2">
    	<tns:domanda nome="D2"/>
  	</tns:classeEsclusione>
  
	<tns:domanda codiceDomanda="D1" precedenza="0">
		<tns:contenutoDomanda>contenutoDomanda1</tns:contenutoDomanda>
		<tns:risposta peso="2">
			<tns:contenutoRisposta>A</tns:contenutoRisposta>
			<tns:classeAppartenenza nome="C1"/>
			<tns:classeAppartenenza nome="C2"/>
       	<tns:classeEsclusione nome="E2"/>
		</tns:risposta>
		<tns:risposta peso="3">
			<tns:contenutoRisposta>B</tns:contenutoRisposta>
			<tns:classeAppartenenza nome="C3"/>
			<tns:classeAppartenenza nome="C4"/>
         <tns:classeEsclusione nome="E2"/>
		</tns:risposta>
		<tns:risposta peso="1">
			<tns:contenutoRisposta>C</tns:contenutoRisposta>
			<tns:classeAppartenenza nome="C1"/>
			<tns:classeAppartenenza nome="C3"/>
		</tns:risposta>
	</tns:domanda>
	
	<tns:domanda codiceDomanda="D2" precedenza="1">
		<tns:contenutoDomanda>contenutoDomanda2</tns:contenutoDomanda>
		<tns:risposta peso="1">
			<tns:contenutoRisposta>A</tns:contenutoRisposta>
			<tns:classeAppartenenza nome="C2"/>
			<tns:classeEsclusione nome="E1"/>
		</tns:risposta>
		<tns:risposta peso="2">
			<tns:contenutoRisposta>B</tns:contenutoRisposta>
			<tns:classeAppartenenza nome="C3"/>
		</tns:risposta>
	</tns:domanda>
  
</tns:questionario>
